Fixed rollback

diff --git a/.github/workflows/rollback.yml b/.github/workflows/rollback.yml
--- a/.github/workflows/rollback.yml
+++ b/.github/workflows/rollback.yml
@@ -56,21 +56,21 @@ jobs:
                   fi
                   echo "Backup number validated: $BACKUP_NUM"
 
-            # - name: Validate Environment and Branch
-            #   run: |
-            #       CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
-            #       INPUT_ENV="${{ github.event.inputs.environment }}"
+            - name: Validate Environment and Branch
+              run: |
+                  CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
+                  INPUT_ENV="${{ github.event.inputs.environment }}"
 
-            #       echo "Checking if branch [$CURRENT_BRANCH] matches environment [$INPUT_ENV]..."
+                  echo "Checking if branch [$CURRENT_BRANCH] matches environment [$INPUT_ENV]..."
 
-            #       if [[ "$CURRENT_BRANCH" == "$INPUT_ENV" ]]; then
-            #           echo "Validation successful."
-            #       else
-            #           echo "ERROR: Environment mismatch!"
-            #           echo "You cannot rollback to '$INPUT_ENV' from the '$CURRENT_BRANCH' branch."
-            #           echo "Please ensure your branch and input environment match."
-            #           exit 1
-            #       fi
+                  if [[ "$CURRENT_BRANCH" == "$INPUT_ENV" ]]; then
+                      echo "Validation successful."
+                  else
+                      echo "ERROR: Environment mismatch!"
+                      echo "You cannot rollback to '$INPUT_ENV' from the '$CURRENT_BRANCH' branch."
+                      echo "Please ensure your branch and input environment match."
+                      exit 1
+                  fi
 
             - name: Display rollback information
               run: |
@@ -115,18 +115,18 @@ jobs:
                   pip install ansible
                   ansible --version
 
-            - name: Get Terraform state for environment
-              id: ip_output
-              run: |
-                  aws s3 cp "s3://${S3_BUCKET}/${STATE_KEY}" terraform.tfstate
-                  echo "vm_ips=$(terraform output -json vm_ips)" >> $GITHUB_OUTPUT
-                  echo "vm_private_ips=$(terraform output -json vm_private_ips)" >> $GITHUB_OUTPUT
-                  rm terraform.tfstate
-              env:
-                  STATE_KEY: "terraform-orbit/${{ env.project }}/${{ env.stage }}/terraform.tfstate"
-                  S3_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
-                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            # - name: Get Terraform state for environment
+            #   id: ip_output
+            #   run: |
+            #       aws s3 cp "s3://${S3_BUCKET}/${STATE_KEY}" terraform.tfstate
+            #       echo "vm_ips=$(terraform output -json vm_ips)" >> $GITHUB_OUTPUT
+            #       echo "vm_private_ips=$(terraform output -json vm_private_ips)" >> $GITHUB_OUTPUT
+            #       rm terraform.tfstate
+            #   env:
+            #       STATE_KEY: "terraform-orbit/${{ env.project }}/${{ env.stage }}/terraform.tfstate"
+            #       S3_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
+            #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+            #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
             - name: Get IP for environment
               id: ip_output
